.PHONY: clean All

All:
	@echo "----------Building project:[ Opdracht2_4 -  ]----------"
	@cd "Opdracht2_4" && "$(MAKE)" -f  "Opdracht2_4.mk"
clean:
	@echo "----------Cleaning project:[ Opdracht2_4 -  ]----------"
	@cd "Opdracht2_4" && "$(MAKE)" -f  "Opdracht2_4.mk" clean
