.PHONY: clean All

All:
	@echo "----------Building project:[ Test_main_to_main_calling - Debug ]----------"
	@cd "Test_main_to_main_calling" && "$(MAKE)" -f  "Test_main_to_main_calling.mk"
clean:
	@echo "----------Cleaning project:[ Test_main_to_main_calling - Debug ]----------"
	@cd "Test_main_to_main_calling" && "$(MAKE)" -f  "Test_main_to_main_calling.mk" clean
